### ISSUE TITLE
Laravel not showing events

### ISSUE THREAD

**Issue by juanjolainez** [In-Touch/laravel-newrelic#13]
Hi, I followed all the instructions and set the configuration as 
'auto_name_transactions' => true

but NewRelic only tracks background processes and errors. And nothing else.
I only have an API (to communicate with my app) and the routes are defined as this:

Route::controller('/api', 'ApiController');

Any thoughts?

**Comment by pleckey** [comment]
Please see the updated [README](https://github.com/In-Touch/laravel-newrelic) for Laravel 5 support, and let me know if this is still an issue.  Also, what version of the NewRelic PHP Agent are you running?
