### ISSUE TITLE
Adds a new option to log errors in newrelic when laravel debug is set to false.

### ISSUE THREAD

**Issue by gvsrepins** [In-Touch/laravel-newrelic#16]
In order to make the errors appear in the Newrelic dashboard when the debug is set to false I need to add the follow snippet to the `app/start/global.php` file:

```
App::error(function(Exception $exception, $code)
{
    Log::error($exception);
    if (App::environment('production'))
    {
        $newrelic = new Intouch\Newrelic\Newrelic;
        $newrelic->noticeError($exception);
    }

});
```

What you think about this be done behind the scenes and bring this as a new option in the package config file?

**Comment by pleckey** [comment]
Hi @gvsrepins - my apologies for letting this go so long un-noticed!  I like the idea - can you submit a PR against the new L5 refactored version?
