### ISSUE TITLE
Simple grammatical error in config publishing step in instructions

### ISSUE THREAD

**Issue by punn** [In-Touch/laravel-newrelic#19]
It should be (for Laravel 4.2 at least)
```
php artisan config:publish intouch/laravel-newrelic
```
and not:
```
php artisan publish:config intouch/laravel-newrelic
```

**Comment by pleckey** [comment]
@punn As seen in PR (https://github.com/In-Touch/laravel-newrelic/pull/18), the master branch is being readied for Laravel 5 (due out this week).  In Laravel 5, the artisan command has been changed to `publish:config`.  The tagged versions released on Packagist have the correct syntax for L4.x.

**Comment by punn** [comment]
@pleckey Sorry about that. Thanks for clearing this up.

**Comment by pleckey** [comment]
@punn no worries, appreciate the input.  :beers:
