### ISSUE TITLE
Wrong Publish Config Artisan Command

### ISSUE THREAD

**Issue by jroman00** [In-Touch/laravel-newrelic#22]
The readme says:

```
php artisan publish:config intouch/laravel-newrelic
```

For me (using Laravel 4.2.17), I had to run:
```
php artisan config:publish intouch/laravel-newrelic
```

**Comment by pleckey** [comment]
@jroman00 please note in the readme:

> dev-master is currently undergoing updates to support Laravel 5
> 
> For Laravel 4.1/4.2 support, please use the latest 1.1.x tag.
> For Laravel 4.0 support, please use the latest 1.0.x tag.

If you look at the readme for the latest 1.1.x tag, the command is correct for Laravel 4.x.  Laravel 5 (current stable Laravel release) has a different command to publish configs.

I will be trying to get the fully L5-compatible version up this weekend, with new functionality as well.  If you're looking for L4 support, please check the tags mentioned in the readme.
