### ISSUE TITLE
Error while installing the package

### ISSUE THREAD

**Issue by mhabibi** [In-Touch/laravel-newrelic#36]
I just created a Laravel 5 project and added this library, now when I run `php artisan` I get this error:

> [BadMethodCallException]  
>   Method after does not exist.

**Comment by stevethomas** [comment]
@mhabibi see this [bug report](https://discuss.newrelic.com/t/php-agent-breaks-laravel-5-2/32801/25)

**Comment by bgetsug** [comment]
It seems that while the fix in #32 was merged, it was never tagged with a new 2.x version. Using the master branch works for me.

**Comment by Jalle19** [comment]
This should be closed as it's no longer an issue.

**Comment by lukewaite** [comment]
This was resolved with the release of the `2.1.0` tag, I believe.
