### ISSUE TITLE
[Request] Enable/Disable based upon environment config.

### ISSUE THREAD

**Issue by kyranb** [In-Touch/laravel-newrelic#39]
It'd be great to conditionally load the service provider based on an environment variable, that way avoiding the 

``` php
 [BadMethodCallException]
  Method after does not exist.
```

error that shows up when this is installed without the New Relic PHP agent being installed.

**Comment by pleckey** [comment]
@kyranb You should be able to handle this with the `throw_if_not_installed` config param:
https://github.com/In-Touch/laravel-newrelic/blob/master/src/config/config.php#L40

Is that not working for you?

**Comment by kyranb** [comment]
@pleckey Yeap, set to false and still getting the above error when running `php artisan`.

**Comment by Jalle19** [comment]
This should be closed as it's no longer an issue.
