### ISSUE TITLE
Not working in Laravel 5.4

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [In-Touch/laravel-newrelic#46]
Call to undefined method Illuminate\Foundation\Application::share()
in Intouch/LaravelNewrelic/NewrelicServiceProvider.php line 54

**Comment by paunin** [comment]
https://github.com/In-Touch/laravel-newrelic/pull/47

**Comment by DanielKeeble** [comment]
@paunin That fix was specifically for Lumen. Would it be possible to get a fix for Laravel?

**Comment by wins1908** [comment]
#49 
@pleckey @DanielKeeble could u merge to master and create a tag?

**Comment by paunin** [comment]
+1

**Comment by kremsy** [comment]
+1

**Comment by honjoya** [comment]
+1  Waiting  the MR from @wins1908

**Comment by jroman00** [comment]
+1

**Comment by pleckey** [comment]
Sorry folks - was stuck between job change (no longer with Intouch), traveling and sick. Intouch have been kind enough to leave me on as an admin for this project though, so I will now be able to keep up-to-date with it again.

PR#49 has been merged to master, and I'll cut a 5.4 tag and update readme shortly.

**Comment by jroman00** [comment]
Any update on creating the new tag?

**Comment by lukewaite** [comment]
@pleckey I can tag this and update if you'd like. Were you thinking `2.2.x` for the 5.4 compatible version?

**Comment by pleckey** [comment]
@jroman00 @lukewaite Tagged 2.2.0 for 5.4 and released.
